<?php
/** Prevent direct access */

defined( 'ABSPATH' ) or exit;


// List of all block names available in this plugin.
// should be autogenerated in the future.
return array(
    'post-terms',
    'post-terms-archive',
    'related-posts',
    'single-publication-details',
);
